import { createElement } from '@lwc/engine-dom';
import LMS_PUB_SUB_Publisher from 'c/lMS_PUB_SUB_Publisher';

describe('c-l-m-s-p-u-b-s-u-b-publisher', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-m-s-p-u-b-s-u-b-publisher', {
            is: LMS_PUB_SUB_Publisher
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});